In [1]:
import torch

In [3]:
t = torch.arange(0, 3*3*3).reshape(3, 3, 3)
print(t)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])


In [4]:
t.max(dim=2)

torch.return_types.max(
values=tensor([[ 2,  5,  8],
        [11, 14, 17],
        [20, 23, 26]]),
indices=tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]))

In [5]:
t.max(dim=1)

torch.return_types.max(
values=tensor([[ 6,  7,  8],
        [15, 16, 17],
        [24, 25, 26]]),
indices=tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]))

In [14]:
v, i = t.max(dim=0)
print(v.max(dim=0)[0])

tensor([24, 25, 26])


In [10]:
t.permute(2, 1, 0)

tensor([[[ 0,  9, 18],
         [ 3, 12, 21],
         [ 6, 15, 24]],

        [[ 1, 10, 19],
         [ 4, 13, 22],
         [ 7, 16, 25]],

        [[ 2, 11, 20],
         [ 5, 14, 23],
         [ 8, 17, 26]]])

In [11]:
t.permute(2, 1, 0).max(dim=2)

torch.return_types.max(
values=tensor([[18, 21, 24],
        [19, 22, 25],
        [20, 23, 26]]),
indices=tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]))

In [ ]:
torch.min(torch.tensor([[1, 10]]), torch.tensor([[2, 9]]))

tensor([[1, 9]])