In [2]:
import torch

In [8]:
import random

def permute_list(lst):
    return random.sample(lst, len(lst))

# Exemple d'utilisation
l = ["a", 2, "c", 4, 5]
l_permuted = permute_list(l)
print(l_permuted)

[2, 'a', 5, 4, 'c']


In [4]:
l = [1, 2, 3, 4, 5]
print(l)
idx_permut = torch.randperm(len(l))
print(idx_permut)
l2 = l[idx_permut.tolist()]
print(l2)


[1, 2, 3, 4, 5]
tensor([2, 3, 1, 0, 4])


TypeError: list indices must be integers or slices, not list

In [10]:
d = {"a": 1, "b": 2, "c":10}
len(d)

3

In [3]:
t = torch.arange(0, 3*3*3).reshape(3, 3, 3)
print(t)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])


In [4]:
t.max(dim=2)

torch.return_types.max(
values=tensor([[ 2,  5,  8],
        [11, 14, 17],
        [20, 23, 26]]),
indices=tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]))

In [5]:
t.max(dim=1)

torch.return_types.max(
values=tensor([[ 6,  7,  8],
        [15, 16, 17],
        [24, 25, 26]]),
indices=tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]))

In [14]:
v, i = t.max(dim=0)
print(v.max(dim=0)[0])

tensor([24, 25, 26])


In [10]:
t.permute(2, 1, 0)

tensor([[[ 0,  9, 18],
         [ 3, 12, 21],
         [ 6, 15, 24]],

        [[ 1, 10, 19],
         [ 4, 13, 22],
         [ 7, 16, 25]],

        [[ 2, 11, 20],
         [ 5, 14, 23],
         [ 8, 17, 26]]])

In [11]:
t.permute(2, 1, 0).max(dim=2)

torch.return_types.max(
values=tensor([[18, 21, 24],
        [19, 22, 25],
        [20, 23, 26]]),
indices=tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]))

In [ ]:
torch.min(torch.tensor([[1, 10]]), torch.tensor([[2, 9]]))

tensor([[1, 9]])

In [ ]:
import sys
import os
from pathlib import Path

IN_COLAB = "google.colab" in sys.modules

repo = "workshop_cs_202503"
branch = "main"
repo_path = (
    "/content"
    if IN_COLAB
    else "./"
    if repo not in os.getcwd()
    else str(next(p for p in Path.cwd().parents if p.name == repo))
)

if Path(root).exists() and not Path(f"{root}").exists():
    if not os.path.exists(f"{root}"):
        !wget -P {root} 'https://github.com/nicolasguillard/workshop_cs_202503/archive/refs/heads/{branch}.zip'
        !unzip {root}/{branch}.zip '{repo}-{branch}/{chapter}/exercises/*' -d {root}
        !mv {root}/{repo}-{branch}/{chapter} {root}/{chapter}
        !rm {root}/{branch}.zip
        !rmdir {root}/{repo}-{branch}

if f"{root}/{chapter}/exercises" not in sys.path:
    sys.path.append(f"{root}/{chapter}/exercises")

os.chdir(f"{root}/{chapter}/exercises")